### ISSUE TITLE
Broken icons

### ISSUE THREAD

**Issue by IonicaBizau** [numixproject/numix-icon-theme-technic#2]
I using the [Numix uTouch icon theme](https://github.com/numixproject/numix-icon-theme-utouch) which is really cool.

I downloaded the repository and moved the folder in `/usr/share/icons`. However there are still some broken icons:

### In the top panel

![image](https://cloud.githubusercontent.com/assets/2864371/5797331/a897a240-9fc0-11e4-9504-25a14ecb4d37.png)

### Folders

![image](https://cloud.githubusercontent.com/assets/2864371/5797335/c10dfd88-9fc0-11e4-9566-453f993cefda.png)

I guess this is not the inteded behavior. How can I fix this?

**Comment by Foggalong** [comment]
This isn't the uTouch icon theme, this is the technic icon theme. [This is the uTouch repo](https://github.com/numixproject/numix-icon-theme-utouch)

**Comment by IonicaBizau** [comment]
I cannot report issues there... :disappointed:

**Comment by Foggalong** [comment]
Should be able to now :)

**Comment by IonicaBizau** [comment]
Done. Thanks! :smile:
